spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/siapm
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/siapm
      password: 123456
      username: postgres
      minimum-idle: 3
      maximum-pool-size: 5
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    servlet:
      path: /api

  # App Properties
siapm:
  app:
    jwtSecret: 3EsiytAVRoL6SaPPBUAl*
    jwtExpirationMs: 86400000
